import rawManifest from "../../public/shots/manifest.json";
import type { ShotsManifest } from "./shots.schema";

export type ShotKey = `${"desktop" | "tablet" | "mobile"}-${"dark" | "light"}` | "full-dark";

export type { ShotEntry, ShotsManifest } from "./shots.schema";

export interface ProjectShots {
    url: string;
    capturedAt: string;
    files: Partial<Record<ShotKey, string>> & Record<string, string>;
}

/**
 * The manifest is generated by scripts/shots.mjs and validated by
 * `ShotsManifestSchema` in shots.test.ts — no runtime parse here, so this module
 * (imported from client components) carries zero zod.
 */
export const manifest: ShotsManifest = rawManifest as ShotsManifest;

export function getShots(slug: string, m: ShotsManifest = manifest): ProjectShots | undefined {
    const entry = m.shots[slug];
    if (!entry) return undefined;
    const files: Record<string, string> = {};
    for (const [key, f] of Object.entries(entry.files)) files[key] = `/${f.path}`;
    return { url: entry.url, capturedAt: entry.capturedAt, files };
}

export function shotSrc(
    slug: string,
    key: ShotKey,
    m: ShotsManifest = manifest,
): string | undefined {
    return getShots(slug, m)?.files[key];
}

export function hasShots(slug: string, m: ShotsManifest = manifest): boolean {
    const entry = m.shots[slug];
    return !!entry && Object.keys(entry.files).length > 0;
}
