// GENERATED by brand/src/build.mjs — do not edit. Keystone mark + wordmark geometry.
// Mark: 48-unit grid. Wordmark: cap height 100, baseline y = 0 (Bricolage Grotesque 720/96/88).
export const MARK = {
    "d": "M10.5 9H24A15 15 0 0 1 24 39H10.5Q8.5 39 8.5 37V11Q8.5 9 10.5 9Z",
    "cStroke": "M27.479 19.822A6.5 6.5 0 1 0 27.479 28.178",
    "knockout": "M10.5 9H24A15 15 0 0 1 24 39H10.5Q8.5 39 8.5 37V11Q8.5 9 10.5 9ZM29.394 18.215A9 9 0 1 0 29.394 29.785L25.564 26.571A4 4 0 1 1 25.564 21.429Z"
} as const;

export const WORDMARK = {
    "viewBox": "-1 -118 788.515 173.75",
    "comma": "M345.803 16.5A9.5 9.5 0 1 1 364.803 16.5C364.803 34.55 353.403 45 344.378 48.325L342.953 44.05C351.028 39.3 355.778 32.65 355.303 25.525A9.5 9.5 0 0 1 345.803 16.5Z",
    "commaCx": 355.303
} as const;

/** Comma-below on its own (for live-text wordmarks): viewBox fits the drop, origin = s centre. */
export const COMMA = {
    "d": "M-9.5 16.5A9.5 9.5 0 1 1 9.5 16.5C9.5 34.55 -1.9 45 -10.925 48.325L-12.35 44.05C-4.275 39.3 0.475 32.65 0 25.525A9.5 9.5 0 0 1 -9.5 16.5Z",
    "viewBox": "-12.35 7 21.85 41.325"
} as const;
